services:
  - type: web
    name: pokerpov
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: development
      - key: VITE_SERVER_URL
        value: https://pokerpov-wocm.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /health